### ISSUE TITLE
Implement panic handler to print message on serial port

### ISSUE THREAD

**Issue by philhug** [oreboot/oreboot#154]
Currently panic just calls wfi on riscv without printing the error message first.

**Comment by rjoleary** [comment]
Good idea! This looks really easy since the PanicInfo struct (https://doc.rust-lang.org/beta/core/panic/struct.PanicInfo.html) already implements the Display trait. So printing it should be as simple as:

```
write!(w, "PANIC: {}\r\n", info);
```

inside of https://github.com/oreboot/oreboot/blob/acd9b98c9f5eb219b5936389321d87448655ab3d/src/arch/riscv/rv64/src/lib.rs#L19

The tricky part is how do we get `w`? I think it would be okay to re-initialize the UART driver here. Under normal circumstances, it would be unsafe to have multiple instances of the UART driver, but these circumstances are special. Particularly, something has already gone wrong to end up in the panic handler and this is a desperate final scream.

There's also something to be said about keeping the dependencies of the panic handler simple. The problem with `write!(w, "PANIC: {}\r\n", info);` is it might depend on a stack. If so, you'd get no output if the stack pointer is invalid. That is probably okay (and as far as I know, there's no way to guarantee the compiler won't use the stack) and would be much better than nothing.

I'll open a quick PR to add it.
