### ISSUE TITLE
fdt parser fails if value is length 0

### ISSUE THREAD

**Issue by philhug** [oreboot/oreboot#155]

**Comment by rjoleary** [comment]
Thanks for investigating this!

@sphinxc0re has been writing a unit test for the fdt parser and/or was looking into using a different parser. This would be a good test case!

**Comment by doriath** [comment]
Is this issue fixed by #266? If the value has length 0, then "Driver" pread will return EOF error (so it has to be handled in special way). Can this be closed, or was it referring to some other issue with length 0?

I am also working on the unit tests in #271, but I do not have the test for length 0 yet.
