### ISSUE TITLE
QEMU-FSP: Refactor FSP Header parser into its own crate and add tests

### ISSUE THREAD

**Issue by rjoleary** [oreboot/oreboot#451]
Specifically, the `find_fsp` function in https://github.com/oreboot/oreboot/blob/main/src/mainboard/emulation/qemu-fsp/src/main.rs#L150 should be refactored into its own crate for re-use by multiple mainboards.

A crate under `src/lib/fsp` would suffice.

**Comment by aquadara** [comment]
Gotta give this a look in the coming week or two

**Comment by aquadara** [comment]
Discussed a bit with @jhand2, I think we'll put common code in `src/vendorcode/fsp/common/` instead of creating `src/lib/fsp`, and find_fsp lives there already. For that reason, this issue was probably a bit out dated when I picked it up, but I'll try to see if we can upstream more (including perhaps templatizing some of the code that uses non-common structs, if possible).

**Comment by aquadara** [comment]
I think this is some mixture of done and obsolete, so closing.
