### ISSUE TITLE
Is qemu-riscv available now?

### ISSUE THREAD

**Issue by YdrMaster** [oreboot/oreboot#568]
I have tried to boot rustsbi-qemu with oreboot but it didn't work. Is there any documentation that can guide me, or is it not available yet?

**Comment by orangecms** [comment]
Hi, thanks for the inquiry!

QEMU with RISC-V support was just released a few days ago:
https://www.qemu.org/2022/04/19/qemu-7-0-0/

We will see that we set up a board in `src/mainboard/emulation/qemu-riscv` with SBI. Would you like to contribute to that?

Note:
Currently, we only have a bit of SBI code so that it just works for the Nezha (`src/mainboard/sunxi/nezha`). That code use some refactoring. :-)

**Comment by YdrMaster** [comment]
Thanks for your answer!

**Comment by orangecms** [comment]
I realized the QEMU 6 also had RISC-V support already. Please try this here out on your machine @YdrMaster:
https://github.com/u-root/cpubinaries/pull/7

**Comment by bwerthmann** [comment]
@YdrMaster please see #622.

**Comment by YdrMaster** [comment]
thx
